include("ComplexIFunTest.jl")
include("FFunTest.jl")
include("IFunTest.jl")
include("ODETest.jl")
include("OperatorTest.jl")
include("SingFunTest.jl")
include("MultivariateTest.jl")
include("SpeedTest.jl")