

println("Fun tests")
include("IFunTest.jl")
include("FFunTest.jl")
include("ComplexIFunTest.jl")
println("ODE tests")
include("ODETest.jl")
include("VectorTest.jl")
include("OperatorTest.jl")
println("Spaces tests")
include("SingularitiesTest.jl")
include("MultivariateTest.jl")
include("SpacesTest.jl")
include("JacobiTest.jl")
include("SpeedTest.jl")
println("Example tests")
include("ExamplesTest.jl")
include("ReadmeTest.jl")