## precompile
function _precompile_()
    #ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Fun,tuple())
    precompile(+,(ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}))
    precompile(-,(ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}))
    precompile(*,(ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}))
    precompile(/,(ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}))

    precompile(ApproxFun.Type, (Type{ApproxFun.Fun},typeof( Base.exp),))
    precompile(ApproxFun.repeated, (Bool,))
    precompile(ApproxFun.setindex!, (ApproxFun.RaggedMatrix{Float64}, Float64, Int64, Int64,))
    precompile(ApproxFun.min, (Int64, ApproxFun.Infinity{Bool},))
    precompile(ApproxFun.in, (Float64, ApproxFun.Segment{Float64},))
    precompile(ApproxFun.trtrs!, (Type{Base.Val{Char(0x00000055)}}, BandedMatrices.BandedMatrix{Float64}, Array{Float64, 1},))
    precompile(ApproxFun.colstop, (ApproxFun.SubOperator{Float64, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Tuple{Int64, Int64}, Tuple{Int64, Int64}}, Int64,))
    precompile(ApproxFun.bbbzeros, (ApproxFun.SubOperator{Float64, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Tuple{Int64, Int64}, Tuple{Int64, Int64}},))
    precompile(ApproxFun.size, (ApproxFun.CachedOperator{Float64, BandedMatrices.BandedMatrix{Float64}, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Tuple{Int64, Int64}}, Int64,))
    precompile(ApproxFun.reindex, (ApproxFun.SubOperator{Float64, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Tuple{Int64, Int64}, Tuple{Int64, Int64}}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Tuple{ApproxFun.Block, ApproxFun.Block},))
    precompile(ApproxFun.chebmult_getindex, (Array{Float64, 1}, Int64, Int64,))
    precompile(ApproxFun.sym_toeplitz_axpy!, (Float64, Float64, Float64, Array{Float64, 1}, Base.UnitRange{Int64}, Base.UnitRange{Int64}, BandedMatrices.BandedMatrix{Float64},))
    precompile(ApproxFun.dirichlettransform!, (Array{Float64, 1},))
    precompile(ApproxFun.pad!, (Array{Float64, 1}, Int64,))
    precompile(ApproxFun.resizedata!, (ApproxFun.QROperator{ApproxFun.CachedOperator{Float64, BandedMatrices.BandedMatrix{Float64}, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Tuple{Int64, Int64}}, Array{Float64, 2}, Float64}, Base.Colon, Int64,))
    precompile(ApproxFun.defaultConversion, (ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}},))
    precompile(ApproxFun.Type, (Type{ApproxFun.CachedOperator}, Type{ApproxFun.BandedBlockBandedMatrix}, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},))
    precompile(ApproxFun.convert, (Type{BandedMatrices.BandedMatrix}, ApproxFun.SubOperator{Float64, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Tuple{Int64, Int64}, Tuple{Int64, Int64}},))
    precompile(ApproxFun.intersect, (ApproxFun.Segment{Float64}, ApproxFun.Segment{Float64},))
    precompile(ApproxFun.conversion_type, (ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}},))
    precompile(ApproxFun.Type, (Type{ApproxFun.ClenshawPlan}, Type{Float64}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Int64, Int64,))
    precompile(ApproxFun.dirichlet_divide_singularity, (Bool, Array{Float64, 1},))
    precompile(ApproxFun.hankel_axpy!, (Float64, Array{Float64, 1}, Base.UnitRange{Int64}, Base.UnitRange{Int64}, BandedMatrices.BandedMatrix{Float64},))
    precompile(ApproxFun.arclength, (ApproxFun.Segment{Float64},))
    precompile(ApproxFun.blockstop, (ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Int64,))
    precompile(ApproxFun.isapprox, (ApproxFun.Segment{Float64}, ApproxFun.Segment{Float64},))
    precompile(ApproxFun.Type, (Type{ApproxFun.RaggedMatrix}, Type{Float64}, Int64, Array{Int64, 1},))
    precompile(ApproxFun.union_rule, (ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}},))
    precompile(ApproxFun.diagindrow, (BandedMatrices.BandedMatrix{Float64}, Base.UnitRange{Int64}, Base.UnitRange{Int64},))
    precompile(ApproxFun.Type, (Type{ApproxFun.RaggedMatrix{Float64}}, Array{Float64, 1}, Array{Int64, 1}, Int64,))
    precompile(ApproxFun.Ac_mul_Bpars, (ApproxFun.QROperatorQ{ApproxFun.QROperator{ApproxFun.CachedOperator{Float64, BandedMatrices.BandedMatrix{Float64}, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Tuple{Int64, Int64}}, Array{Float64, 2}, Float64}, Float64}, Array{Float64, 1}, Float64, Int64,))
    precompile(ApproxFun.dirichlet_divide_singularity, (Array{Float64, 1},))
    precompile(ApproxFun.coefficients, (Array{Float64, 1}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}},))
    precompile(ApproxFun.transformtimes, (ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Int64,))
    precompile(ApproxFun.blockbandwidth, (ApproxFun.SubOperator{Float64, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Tuple{Int64, Int64}, Tuple{Int64, Int64}}, Int64,))
    precompile(ApproxFun.pad, (Array{Float64, 2}, Int64, Int64,))
    precompile(ApproxFun.Type, (Type{ApproxFun.ConcreteMultiplication}, ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}},))
    precompile(ApproxFun.hasfasttransformtimes, (ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},))
    precompile(ApproxFun.convert, (Type{ApproxFun.Line}, ApproxFun.ClosedInterval{Float64},))
    precompile(ApproxFun.pad, (Array{Float64, 1}, Int64,))
    precompile(ApproxFun.banded_colstop, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Int64,))
    precompile(ApproxFun.clenshaw, (ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Array{Float64, 1}, Float64,))
    precompile(ApproxFun.Type, (Type{ApproxFun.Ray}, Float64, Float64, Bool,))
    precompile(ApproxFun.zerocfsFun, (typeof( Base.exp), ApproxFun.Chebyshev{ApproxFun.Segment{Float64}},))
    precompile(ApproxFun.isbanded, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},))
    precompile(ApproxFun.setdiff, (ApproxFun.Segment{Float64}, Array{Float64, 1},))
    precompile(ApproxFun.points, (ApproxFun.Segment{Float64}, Int64,))
    precompile(ApproxFun.bandwidths, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},))
    precompile(ApproxFun.resizedata!, (ApproxFun.CachedOperator{Float64, BandedMatrices.BandedMatrix{Float64}, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Tuple{Int64, Int64}}, Int64, Base.Colon,))
    precompile(ApproxFun.israggedbelow, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},))
    precompile(ApproxFun.blockbandwidth, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Int64,))
    precompile(ApproxFun.hastrivialblocks, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},))
    precompile(ApproxFun.choosedomainspace, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}},))
    precompile(ApproxFun.Type, (Type{ApproxFun.Fun},typeof( Base.identity),))
    precompile(ApproxFun.points, (ApproxFun.ClosedInterval{Float64}, Int64,))
    precompile(ApproxFun.blockbanded_colstop, (ApproxFun.ConstantOperator{Float64, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}}, Int64,))
    precompile(ApproxFun.union, (ApproxFun.Segment{Float64}, ApproxFun.Segment{Float64},))
    precompile(ApproxFun.getindex, (ApproxFun.QROperator{ApproxFun.CachedOperator{Float64, BandedMatrices.BandedMatrix{Float64}, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Tuple{Int64, Int64}}, Array{Float64, 2}, Float64}, Symbol,))
    precompile(ApproxFun.fromcanonical, (ApproxFun.Segment{Float64}, Float64,))
    precompile(ApproxFun.isambiguous, (ApproxFun.Segment{Float64},))
    precompile(ApproxFun.isbandedblockbanded, (ApproxFun.SubOperator{Float64, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Tuple{Int64, Int64}, Tuple{Int64, Int64}},))
    precompile(ApproxFun.checkbounds, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Base.UnitRange{Int64}, Base.UnitRange{Int64},))
    precompile(ApproxFun.view, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Base.UnitRange{Int64}, Base.UnitRange{Int64},))
    precompile(ApproxFun.defaultFun, (Type{Float64}, Function, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Array{Float64, 1}, Type{Base.Val{false}},))
    precompile(ApproxFun.unstructured_colstop, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Int64,))
    precompile(ApproxFun.blockbanded_colstop, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Int64,))
    precompile(ApproxFun.default_blockbandedmatrix, (ApproxFun.SubOperator{Float64, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Tuple{Int64, Int64}, Tuple{Int64, Int64}},))
    precompile(ApproxFun.Type, (Type{ApproxFun.Take{ApproxFun.Repeated{Bool}, Bool}}, ApproxFun.Repeated{Bool}, Int64,))
    precompile(ApproxFun.isblockbanded, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},))
    precompile(ApproxFun.defaultFun, (typeof( Base.exp), ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Int64, Type{Base.Val{false}},))
    precompile(ApproxFun.alternatingsum, (Array{Float64, 1},))
    precompile(ApproxFun.unstructured_colstop, (ApproxFun.ConstantOperator{Float64, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}}, Int64,))
    precompile(ApproxFun.colleague_matrix, (Array{Float64, 1},))
    precompile(ApproxFun.convert, (Type{ApproxFun.RaggedMatrix}, BandedMatrices.BandedMatrix{Float64},))
    precompile(ApproxFun.fromcanonicalD, (ApproxFun.Segment{Float64}, Float64,))
    precompile(ApproxFun.hasconstblocks, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},))
    precompile(ApproxFun.subblockbandinds, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Int64,))
    precompile(ApproxFun.blockbandinds, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},))
    precompile(ApproxFun.rootsunit_coeffs, (Array{Float64, 1}, Float64, ApproxFun.ClenshawPlan{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},))
    precompile(ApproxFun.roots, (ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},))
    precompile(ApproxFun.PruneOptions, (Array{Base.Complex{Float64}, 1}, Float64,))
    precompile(ApproxFun.domainscompatible, (ApproxFun.Segment{Float64}, ApproxFun.Segment{Float64},))
    precompile(ApproxFun.A_mul_B_coefficients, (ApproxFun.SubOperator{Float64, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Tuple{Int64, Int64}, Tuple{Int64, Int64}}, Array{Float64, 1},))
    precompile(ApproxFun.view, (ApproxFun.ConstantOperator{Float64, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}}, Type{ApproxFun.FiniteRange}, Base.UnitRange{Int64},))
    precompile(ApproxFun.Type, (Type{ApproxFun.Fun{ApproxFun.ChebyshevDirichlet{1, 1, ApproxFun.Segment{Float64}}, Float64}}, ApproxFun.ChebyshevDirichlet{1, 1, ApproxFun.Segment{Float64}}, Array{Float64, 1},))
    precompile(ApproxFun.Fun, (ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Float64,))
    precompile(ApproxFun.Type, (Type{ApproxFun.Fun}, Float64, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}},))
    precompile(ApproxFun.bandedblockbanded_colstop, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Int64,))
    precompile(ApproxFun.defaultcoefficients, (Array{Float64, 1}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}},))
    precompile(ApproxFun.bandedblockbanded_colstop, (ApproxFun.ConstantOperator{Float64, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}}, Int64,))
    precompile(ApproxFun.divide_singularity, (Tuple{Int64, Int64}, ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},))
    precompile(ApproxFun.Type, (Type{ApproxFun.Fun}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Array{Float64, 1},))
    precompile(ApproxFun.Type, (Type{ApproxFun.Block}, Int64,))
    precompile(ApproxFun.valsdomain_type_promote, (Type{Float64}, Type{Float64},))
    precompile(ApproxFun.ncoefficients, (ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},))
    precompile(ApproxFun.chop!, (ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Float64,))
    precompile(ApproxFun.chop!, (Array{Float64, 1}, Float64,))
    precompile(ApproxFun.blockstart, (ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Int64,))
    precompile(ApproxFun.convert, (Type{ApproxFun.RaggedMatrix}, ApproxFun.SubOperator{Float64, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Tuple{Int64, Int64}, Tuple{Int64, Int64}},))
    precompile(ApproxFun.rootsunit_coeffs, (Array{Float64, 1}, Float64,))
    precompile(ApproxFun.getindex, (ApproxFun.Segment{Float64}, Base.IteratorsMD.CartesianIndex{0},))
    precompile(ApproxFun.view, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Type{ApproxFun.FiniteRange}, Base.UnitRange{Int64},))
    precompile(ApproxFun.convert, (Type{ApproxFun.Ray}, ApproxFun.ClosedInterval{Float64},))
    precompile(ApproxFun.A_mul_B_coefficients, (ApproxFun.ConstantOperator{Float64, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}}, Array{Float64, 1},))
    precompile(ApproxFun.transform, (ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Array{Float64, 1},))
    precompile(ApproxFun.default_raggedmatrix, (ApproxFun.SubOperator{Float64, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Tuple{Int64, Int64}, Tuple{Int64, Int64}},))
    precompile(ApproxFun.default_colstop, (ApproxFun.ConstantOperator{Float64, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}}, Int64,))
    precompile(ApproxFun.Type, (Type{ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Array{Float64, 1},))
    precompile(ApproxFun.getindex, (ApproxFun.SubOperator{Float64, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Tuple{Int64, Int64}, Tuple{Int64, Int64}}, Int64, Int64,))
    precompile(ApproxFun.rzeros, (Type{Float64}, Int64, Array{Int64, 1},))
    precompile(ApproxFun.Type, (Type{ApproxFun.IChebyshevTransformPlan{Float64, 1, true, Base.DFT.FFTW.r2rFFTWPlan{Float64, (4,), true, 1}}}, Base.DFT.FFTW.r2rFFTWPlan{Float64, (4,), true, 1},))
    precompile(ApproxFun.Type, (Type{ApproxFun.IChebyshevTransformPlan{Float64, 1, false, ApproxFun.IChebyshevTransformPlan{Float64, 1, true, Base.DFT.FFTW.r2rFFTWPlan{Float64, (4,), true, 1}}}}, ApproxFun.IChebyshevTransformPlan{Float64, 1, true, Base.DFT.FFTW.r2rFFTWPlan{Float64, (4,), true, 1}},))
    precompile(ApproxFun.Type, (Type{ApproxFun.Fun{ApproxFun.JacobiWeight{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Segment{Float64}}, Float64}}, ApproxFun.JacobiWeight{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Segment{Float64}}, Array{Float64, 1},))
    precompile(ApproxFun.A_mul_B_coefficients, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Array{Float64, 1},))
    precompile(ApproxFun.Type, (Type{ApproxFun.ChebyshevTransformPlan{Float64, 1, true, Base.DFT.FFTW.r2rFFTWPlan{Float64, (5,), true, 1}}}, Base.DFT.FFTW.r2rFFTWPlan{Float64, (5,), true, 1},))
    precompile(ApproxFun.evaluate, (ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Float64,))
    precompile(ApproxFun.convert, (Type{ApproxFun.BlockBandedMatrix}, ApproxFun.SubOperator{Float64, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Tuple{Int64, Int64}, Tuple{Int64, Int64}},))
    precompile(ApproxFun.divide_singularity, (ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},))
    precompile(ApproxFun.default_colstop, (ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, Int64,))
    precompile(ApproxFun.banded_colstop, (ApproxFun.ConstantOperator{Float64, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}}, Int64,))
    precompile(ApproxFun.A_ldiv_B_coefficients, (ApproxFun.QROperatorR{ApproxFun.QROperator{ApproxFun.CachedOperator{Float64, BandedMatrices.BandedMatrix{Float64}, ApproxFun.ConcreteMultiplication{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Tuple{Int64, Int64}}, Array{Float64, 2}, Float64}, Float64}, Array{Float64, 1},))
    precompile(ApproxFun.identity_fun, (ApproxFun.Segment{Float64},))
    precompile(ApproxFun.divide_singularity, (Bool, ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},))
    precompile(ApproxFun.union, (ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}},))
    precompile(ApproxFun.convert, (Type{ApproxFun.Domain}, ApproxFun.ClosedInterval{Float64},))
    precompile(ApproxFun.coefficients, (ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, ApproxFun.Chebyshev{ApproxFun.Segment{Float64}},))
    precompile(ApproxFun.setdiff, (ApproxFun.Segment{Float64}, ApproxFun.Point{Float64},))
    precompile(ApproxFun.unsafe_resize!, (Array{Float64, 2}, Base.Colon, Int64,))
    precompile(ApproxFun.coefficients, (ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64}, ApproxFun.ChebyshevDirichlet{1, 1, ApproxFun.Segment{Float64}},))
    precompile(ApproxFun.pad!, (BandedMatrices.BandedMatrix{Float64}, Int64, Int64,))
    precompile(ApproxFun.splitatroots, (ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Segment{Float64}}, Float64},))
    precompile(ApproxFun.Type, (Type{ApproxFun.Fun},))
end
